//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.10 at 09:06:10 PM CET 
//


package cz.velim.jaxbexample.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MainServer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoadClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "type",
    "mainServer",
    "loadClass"
})
@XmlRootElement(name = "Config")
public class Config {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "MainServer", required = true)
    protected String mainServer;
    @XmlElement(name = "LoadClass", required = true)
    protected String loadClass;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the mainServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainServer() {
        return mainServer;
    }

    /**
     * Sets the value of the mainServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainServer(String value) {
        this.mainServer = value;
    }

    /**
     * Gets the value of the loadClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadClass() {
        return loadClass;
    }

    /**
     * Sets the value of the loadClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadClass(String value) {
        this.loadClass = value;
    }

}
